services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payments-services-api
    environment:
      APP_PORT: 7104
      ConnectionStrings__ConnectionPostgre: "Host=db;Port=5432;Database=payments_service;Username=postgres;Password=ChangeMeStrong!123"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "7104:7104"
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: payments-services-db
    environment:
      POSTGRES_DB: payments_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ChangeMeStrong!123
    ports:
      - "5532:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  postgres-data: